export const PLACEHOLDERS = {
    SEARCH_INPUT: 'Название или ингредиент...',
    SELECT: 'Выберите из списка...',
    SELECT_DRAWER: 'Выберите из списка аллергенов...',
    BUTTON_ADD_OTHER_ALLERGEN: 'Другой аллерген',
    BUTTON_EXCLUDE_ALLERGENS: 'Исключить аллергены',
    RECIPE_NAME: 'Название рецепта',
    LITTLE_RECIPE_DESCRIPTION: 'Краткое описание рецепта',
    INGREDIENT: 'Ингредиент',
    STEP: 'Опишите шаг...',
    INGREDIENTS_COUNT: '100',
    INGREDIENTS_MEASURE_UNIT: 'Единица измерения',
    SIGN_UP_LOGIN: 'Логин',
    SIGN_IN_LOGIN: 'Введите логин',
    PASSWORD: 'Пароль для сайта',
    REPEAT_PASSWORD: 'Повторите пароль',
    EMAIL: 'e-mail',
    NAME: 'Имя',
    SURNAME: 'Фамилия',
    MAX_LENGTH_TEXTAREA: 'Максимально 160 символов',
    OLD_PASSWORD: 'Старый пароль',
    NEW_PASSWORD: 'Новый пароль',
};
